# === Local Profile ===

# Schema init
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# CORS
cors.allowed-origins=http://localhost:5173

# MyBatis SQL logging
logging.level.com.tcb_server=DEBUG
